### ISSUE TITLE
Unable to get transform classes to show up in my compiled CSS file.

### ISSUE THREAD

**Issue by HamzaMoiyadi** [benface/tailwindcss-transforms#16] opened 2019-12-29 10:30 UTC
I've added the tailwindcss-transform package as a plugin in my tailwind.config.js file, and even though the postcss build passes without any issues, I can't seem to see the classes in my compiled, minified style.css. 
Is there any other pre-requisite I'm missing? facing this same issue in another Nuxt project I'm working on.

**Comment by benface** [comment] 2020-01-02 14:44
@HamzaMoiyadi Can you please share your Tailwind config? Also, are you using something like Purgecss?

**Comment by HamzaMoiyadi** [comment] 2020-01-02 15:25
[config.txt](https://github.com/benface/tailwindcss-transforms/files/4016334/config.txt)

And no, i'm not using PurgeCSS

**Comment by benface** [comment] 2020-01-02 15:40
@HamzaMoiyadi I tried your config and other than the undefined `system` variable used in two places (I just removed those lines), it compiled fine and I could see classes such as `transform-none`, `transform-t`, `transform-tr`, etc. in the compiled CSS.

**Comment by HamzaMoiyadi** [comment] 2020-01-03 09:00
attaching my postcss config as well. 

`module.exports = {
    plugins: [
        require('postcss-import'),
        require('autoprefixer'),
        require('tailwindcss'),
        require('postcss-fail-on-warn')
    ]
}`

**Comment by benface** [comment] 2020-01-03 15:19
@HamzaMoiyadi Actually would you mind sharing a simple repo that reproduces the issue? I don't see anything in that list of PostCSS plugins that would affect this Tailwind plugin in particular. I suspect something else is going on.

**Comment by HamzaMoiyadi** [comment] 2020-01-06 04:31
https://github.com/HamzaMoiyadi/mercenaries-design-system

^Here's the public repo containing the files I'm using.

**Comment by benface** [comment] 2020-01-06 18:25
@HamzaMoiyadi If I add `transforms()` to the `plugins` array in `tailwind.config.js` and recompile with `yarn build:full`, I see the `transform-` classes in `build/style.css` as expected.

**Comment by HamzaMoiyadi** [comment] 2020-01-10 16:14
Is there anything else that I might be doing wrong? :(

**Comment by benface** [comment] 2020-01-11 19:40
@HamzaMoiyadi I don't understand what you mean. Did you try adding `transforms()` to the `plugins` array? Is that not the issue?

**Comment by benface** [comment] 2020-01-22 21:01
@HamzaMoiyadi Can you confirm that you're still experiencing this issue even after adding `transforms()` to the `plugins` array in that repo you shared?

**Comment by benface** [comment] 2020-01-30 14:02
Closing this as I can't reproduce the issue, feel free to reopen with more details if you're still experiencing it.

**Closed by benface** 2020-01-30 14:02 UTC
